USE [DBTCC]
GO

/****** Object:  Table [dbo].[USUARIO]    Script Date: 08/22/2015 14:11:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[USUARIO](
	[ID_USUARIO] [int] IDENTITY(1,1) NOT NULL,
	[LOGIN_USU] [varchar](20) NOT NULL,
	[SENHA_USU] [varchar](10) NOT NULL,
 CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [DBTCC]
GO

/****** Object:  Table [dbo].[RESPONSAVEL]    Script Date: 08/22/2015 14:11:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[RESPONSAVEL](
	[ID_USUARIO] [int] NOT NULL,
	[NOME] [varchar](40) NOT NULL,
	[SEXO] [char](1) NOT NULL,
 CONSTRAINT [PK_RESPONSAVEL] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[RESPONSAVEL]  WITH CHECK ADD  CONSTRAINT [FK_RESPONSAVEL_USUARIO] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[USUARIO] ([ID_USUARIO])
GO

ALTER TABLE [dbo].[RESPONSAVEL] CHECK CONSTRAINT [FK_RESPONSAVEL_USUARIO]
GO

ALTER TABLE [dbo].[RESPONSAVEL]  WITH CHECK ADD  CONSTRAINT [CK_RESPONSAVEL_SEXO] CHECK  (([SEXO]='M' OR [SEXO]='F'))
GO

ALTER TABLE [dbo].[RESPONSAVEL] CHECK CONSTRAINT [CK_RESPONSAVEL_SEXO]
GO

USE [DBTCC]
GO

/****** Object:  Table [dbo].[CONDUTOR]    Script Date: 08/22/2015 14:11:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CONDUTOR](
	[ID_USUARIO] [int] NOT NULL,
	[NOME] [varchar](40) NOT NULL,
 CONSTRAINT [PK_CONDUTOR] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CONDUTOR]  WITH CHECK ADD  CONSTRAINT [FK_CONDUTOR_USUARIO] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[USUARIO] ([ID_USUARIO])
GO

ALTER TABLE [dbo].[CONDUTOR] CHECK CONSTRAINT [FK_CONDUTOR_USUARIO]
GO