USE [master]
GO

/****** Object:  Database [DBTCC]    Script Date: 08/22/2015 14:20:14 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'DBTCC')
DROP DATABASE [DBTCC]
GO

USE [master]
GO

/****** Object:  Database [DBTCC]    Script Date: 08/22/2015 14:20:14 ******/
CREATE DATABASE [DBTCC] ON  PRIMARY 
( NAME = N'DBTCC', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\DBTCC.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DBTCC_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\DBTCC_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DBTCC] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBTCC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBTCC] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBTCC] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBTCC] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBTCC] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBTCC] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBTCC] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBTCC] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DBTCC] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBTCC] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBTCC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBTCC] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBTCC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBTCC] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBTCC] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBTCC] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBTCC] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBTCC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBTCC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBTCC] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBTCC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBTCC] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBTCC] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBTCC] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBTCC] SET  READ_WRITE 
GO

ALTER DATABASE [DBTCC] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DBTCC] SET  MULTI_USER 
GO

ALTER DATABASE [DBTCC] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBTCC] SET DB_CHAINING OFF 
GO


