USE [DBTCC]
GO

--Drop Constraints
ALTER TABLE [dbo].[CONDUTOR] DROP CONSTRAINT [FK_CONDUTOR_USUARIO]
GO

ALTER TABLE [dbo].[CONDUTOR] DROP CONSTRAINT [FK_CONDUTOR_ENDERECO]
GO

ALTER TABLE [dbo].[ALUNO] DROP CONSTRAINT [FK_ALUNO_ENDERECO]
GO

ALTER TABLE [dbo].[RESPONSAVEL] DROP CONSTRAINT [CK_RESPONSAVEL_SEXO]
GO

ALTER TABLE [dbo].[RESPONSAVEL] DROP CONSTRAINT [FK_RESPONSAVEL_USUARIO]
GO

ALTER TABLE [dbo].[RESPONSAVEL] DROP CONSTRAINT [FK_CONDUTOR_RESPONSAVEL]
GO

ALTER TABLE [dbo].[ALUNO_RESPONSAVEL] DROP CONSTRAINT [FK_ALUNO_RESPONSAVEL_RESPONSAVEL]
GO

ALTER TABLE [dbo].[ALUNO_RESPONSAVEL] DROP CONSTRAINT [FK_ALUNO_RESPONSAVEL_ALUNO]
GO

ALTER TABLE [dbo].[PAGAMENTO] DROP CONSTRAINT [FK_PAGAMENTO_RESPONSAVEL]
GO

/****** Object:  Table [dbo].[ENDERECO]    Script Date: 09/10/2015 17:53:09 ******/
DROP TABLE [dbo].[ENDERECO]
GO

/****** Object:  Table [dbo].[ENDERECO]    Script Date: 09/10/2015 17:53:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ENDERECO](
	[ID_ENDERECO] [int] IDENTITY(1,1) NOT NULL,
	[LOGRADOURO] [varchar](500) NULL,
	[NUMERO] [varchar](10) NULL,
	[COMPLEMENTO] [varchar](10) NULL,
	[BAIRRO] [varchar](50) NULL,
	[CIDADE] [varchar](50) NULL,
	[UF] [char](2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ENDERECO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [DBTCC]
GO

/****** Object:  Table [dbo].[USUARIO]    Script Date: 09/10/2015 17:53:54 ******/
DROP TABLE [dbo].[USUARIO]
GO

/****** Object:  Table [dbo].[USUARIO]    Script Date: 09/10/2015 17:53:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[USUARIO](
	[ID_USUARIO] [int] IDENTITY(1,1) NOT NULL,
	[LOGIN_USU] [varchar](20) NOT NULL,
	[SENHA_USU] [varchar](10) NOT NULL,
	[TELEFONE] [varchar](15) NOT NULL,
 CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [DBTCC]
GO

/****** Object:  Table [dbo].[CONDUTOR]    Script Date: 09/10/2015 17:52:50 ******/
DROP TABLE [dbo].[CONDUTOR]
GO

/****** Object:  Table [dbo].[CONDUTOR]    Script Date: 09/10/2015 17:52:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CONDUTOR](
	[ID_USUARIO] [int] NOT NULL,
	[NOME] [varchar](40) NOT NULL,
	[ID_ENDERECO] [int] NOT NULL,
 CONSTRAINT [PK_CONDUTOR] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CONDUTOR]  WITH CHECK ADD  CONSTRAINT [FK_CONDUTOR_ENDERECO] FOREIGN KEY([ID_ENDERECO])
REFERENCES [dbo].[ENDERECO] ([ID_ENDERECO])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[CONDUTOR] CHECK CONSTRAINT [FK_CONDUTOR_ENDERECO]
GO

ALTER TABLE [dbo].[CONDUTOR]  WITH CHECK ADD  CONSTRAINT [FK_CONDUTOR_USUARIO] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[USUARIO] ([ID_USUARIO])
GO

ALTER TABLE [dbo].[CONDUTOR] CHECK CONSTRAINT [FK_CONDUTOR_USUARIO]
GO

USE [DBTCC]
GO

/****** Object:  Table [dbo].[ALUNO]    Script Date: 09/10/2015 17:52:05 ******/
DROP TABLE [dbo].[ALUNO]
GO

/****** Object:  Table [dbo].[ALUNO]    Script Date: 09/10/2015 17:52:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ALUNO](
	[ID_ALUNO] [int] NOT NULL,
	[NOME] [nchar](10) NOT NULL,
	[DATA_NASC] [datetime] NOT NULL,
	[ID_MODALIDADE] [int] NOT NULL,
	[MODALIDADE] [char](1) NOT NULL,
	[PERIODO] [char](1) NOT NULL,
	[DESTINO] [varchar](50) NOT NULL,
	[OBS] [varchar](100) NULL,
	[ID_ENDERECO] [int] NOT NULL,
 CONSTRAINT [PK_ALUNO] PRIMARY KEY CLUSTERED 
(
	[ID_ALUNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ALUNO]  WITH CHECK ADD  CONSTRAINT [FK_ALUNO_ENDERECO] FOREIGN KEY([ID_ENDERECO])
REFERENCES [dbo].[ENDERECO] ([ID_ENDERECO])
GO

ALTER TABLE [dbo].[ALUNO] CHECK CONSTRAINT [FK_ALUNO_ENDERECO]
GO

USE [DBTCC]
GO

/****** Object:  Table [dbo].[RESPONSAVEL]    Script Date: 09/10/2015 17:53:43 ******/
DROP TABLE [dbo].[RESPONSAVEL]
GO

/****** Object:  Table [dbo].[RESPONSAVEL]    Script Date: 09/10/2015 17:53:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[RESPONSAVEL](
	[ID_USUARIO] [int] NOT NULL,
	[NOME] [varchar](40) NOT NULL,
	[SEXO] [char](1) NOT NULL,
	[ID_ENDERECO] [int] NOT NULL,
 CONSTRAINT [PK_RESPONSAVEL] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[RESPONSAVEL]  WITH CHECK ADD  CONSTRAINT [FK_CONDUTOR_RESPONSAVEL] FOREIGN KEY([ID_ENDERECO])
REFERENCES [dbo].[ENDERECO] ([ID_ENDERECO])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[RESPONSAVEL] CHECK CONSTRAINT [FK_CONDUTOR_RESPONSAVEL]
GO

ALTER TABLE [dbo].[RESPONSAVEL]  WITH CHECK ADD  CONSTRAINT [FK_RESPONSAVEL_USUARIO] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[USUARIO] ([ID_USUARIO])
GO

ALTER TABLE [dbo].[RESPONSAVEL] CHECK CONSTRAINT [FK_RESPONSAVEL_USUARIO]
GO

ALTER TABLE [dbo].[RESPONSAVEL]  WITH CHECK ADD  CONSTRAINT [CK_RESPONSAVEL_SEXO] CHECK  (([SEXO]='M' OR [SEXO]='F'))
GO

ALTER TABLE [dbo].[RESPONSAVEL] CHECK CONSTRAINT [CK_RESPONSAVEL_SEXO]
GO

USE [DBTCC]
GO

/****** Object:  Table [dbo].[ALUNO_RESPONSAVEL]    Script Date: 09/10/2015 17:52:20 ******/
DROP TABLE [dbo].[ALUNO_RESPONSAVEL]
GO

/****** Object:  Table [dbo].[ALUNO_RESPONSAVEL]    Script Date: 09/10/2015 17:52:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ALUNO_RESPONSAVEL](
	[ID_ALN_RESP] [int] IDENTITY(1,1) NOT NULL,
	[ID_ALUNO] [int] NOT NULL,
	[ID_RESPONSAVEL] [int] NOT NULL,
	[PARENTESCO] [varchar](10) NOT NULL,
 CONSTRAINT [PK_ALUNO_RESPONSAVEL] PRIMARY KEY CLUSTERED 
(
	[ID_ALN_RESP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ALUNO_RESPONSAVEL]  WITH CHECK ADD  CONSTRAINT [FK_ALUNO_RESPONSAVEL_ALUNO] FOREIGN KEY([ID_ALUNO])
REFERENCES [dbo].[ALUNO] ([ID_ALUNO])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ALUNO_RESPONSAVEL] CHECK CONSTRAINT [FK_ALUNO_RESPONSAVEL_ALUNO]
GO

ALTER TABLE [dbo].[ALUNO_RESPONSAVEL]  WITH CHECK ADD  CONSTRAINT [FK_ALUNO_RESPONSAVEL_RESPONSAVEL] FOREIGN KEY([ID_RESPONSAVEL])
REFERENCES [dbo].[RESPONSAVEL] ([ID_USUARIO])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ALUNO_RESPONSAVEL] CHECK CONSTRAINT [FK_ALUNO_RESPONSAVEL_RESPONSAVEL]
GO

USE [DBTCC]
GO

/****** Object:  Table [dbo].[PAGAMENTO]    Script Date: 09/10/2015 17:53:25 ******/
DROP TABLE [dbo].[PAGAMENTO]
GO

/****** Object:  Table [dbo].[PAGAMENTO]    Script Date: 09/10/2015 17:53:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PAGAMENTO](
	[ID_PAGAMENTO] [int] NOT NULL,
	[VALOR_PAGO] [money] NOT NULL,
	[ID_RESPONSAVEL] [int] NOT NULL,
	[VENCIMENTO] [datetime] NOT NULL,
 CONSTRAINT [PK_PAGAMENTO] PRIMARY KEY CLUSTERED 
(
	[ID_PAGAMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[PAGAMENTO] ADD  DEFAULT ((0.00)) FOR [VALOR_PAGO]
GO

ALTER TABLE [dbo].[PAGAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_PAGAMENTO_RESPONSAVEL] FOREIGN KEY([ID_RESPONSAVEL])
REFERENCES [dbo].[RESPONSAVEL] ([ID_USUARIO])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[PAGAMENTO] CHECK CONSTRAINT [FK_PAGAMENTO_RESPONSAVEL]
GO