
------------------- INSERE USUÁRIOS -------------------
IF NOT EXISTS (SELECT TOP 1 1 FROM USUARIO WHERE LOGIN_USU IN ('Mot1', 'Res1'))
INSERT INTO USUARIO(LOGIN_USU, SENHA_USU, TELEFONE)
	VALUES	('Mot1', '123456', '(11) 11111-1111'),
			('Res1', '123456', '(11) 11111-1111')

------------------ INSERE ENDEREÇOS ------------------
IF ((SELECT COUNT(*) FROM ENDERECO) < 3)
INSERT INTO ENDERECO (LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, UF)
	VALUES	('Rua x', 1, NULL, 'Centro', 'São Paulo', 'SP'),
			('Rua Y', 2, NULL, 'Centro', 'São Paulo', 'SP'),
			('Rua z', 3, NULL, 'Centro', 'São Paulo', 'SP')

------------------ INSERE CONDUTORES -----------------
CREATE TABLE #TMP_USU(ID_USUARIO INT)
INSERT INTO #TMP_USU
SELECT ID_USUARIO FROM USUARIO 

IF NOT EXISTS (SELECT TOP 1 1 FROM CONDUTOR A JOIN #TMP_USU B ON A.ID_USUARIO = B.ID_USUARIO)
INSERT INTO CONDUTOR(NOME, ID_ENDERECO)
	VALUES('João da Silva', 1)
